# TCL File Generated by Component Editor 18.1
# Wed Mar 04 15:23:40 GMT 2020
# DO NOT MODIFY


# 
# sincos_cordic "sincos_cordic" v1.0
#  2020.03.04.15:23:40
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module sincos_cordic
# 
set_module_property DESCRIPTION ""
set_module_property NAME sincos_cordic
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME sincos_cordic
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL sincos_cordic
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file sincos_cordic.v VERILOG PATH ip/cordic/sincos_cordic.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point sincos_cordic
# 
add_interface sincos_cordic nios_custom_instruction end
set_interface_property sincos_cordic clockCycle 0
set_interface_property sincos_cordic operands 2
set_interface_property sincos_cordic ENABLED true
set_interface_property sincos_cordic EXPORT_OF ""
set_interface_property sincos_cordic PORT_NAME_MAP ""
set_interface_property sincos_cordic CMSIS_SVD_VARIABLES ""
set_interface_property sincos_cordic SVD_ADDRESS_GROUP ""

add_interface_port sincos_cordic a a Input 5
add_interface_port sincos_cordic b b Input 5
add_interface_port sincos_cordic c c Input 5
add_interface_port sincos_cordic reset reset Input 1
add_interface_port sincos_cordic clk clk Input 1

