# TCL File Generated by Component Editor 19.1
# Fri Mar 20 16:13:24 CET 2020
# DO NOT MODIFY


# 
# sincos_cordic "sincos_cordic" v1.0
#  2020.03.20.16:13:24
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module sincos_cordic
# 
set_module_property DESCRIPTION ""
set_module_property NAME sincos_cordic
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME sincos_cordic
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL CORDIC
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file sincos_cordic.v VERILOG PATH ip/cordic/sincos_cordic.v


# 
# parameters
# 
add_parameter XY_SZ INTEGER 16
set_parameter_property XY_SZ DEFAULT_VALUE 16
set_parameter_property XY_SZ DISPLAY_NAME XY_SZ
set_parameter_property XY_SZ TYPE INTEGER
set_parameter_property XY_SZ UNITS None
set_parameter_property XY_SZ ALLOWED_RANGES -2147483648:2147483647
set_parameter_property XY_SZ HDL_PARAMETER true


# 
# display items
# 


# 
# connection point nios_custom_instruction_slave
# 
add_interface nios_custom_instruction_slave nios_custom_instruction end
set_interface_property nios_custom_instruction_slave clockCycle 0
set_interface_property nios_custom_instruction_slave operands 2
set_interface_property nios_custom_instruction_slave ENABLED true
set_interface_property nios_custom_instruction_slave EXPORT_OF ""
set_interface_property nios_custom_instruction_slave PORT_NAME_MAP ""
set_interface_property nios_custom_instruction_slave CMSIS_SVD_VARIABLES ""
set_interface_property nios_custom_instruction_slave SVD_ADDRESS_GROUP ""

add_interface_port nios_custom_instruction_slave deg dataa Input 32
add_interface_port nios_custom_instruction_slave Xout result Output 17
add_interface_port nios_custom_instruction_slave clock clk Input 1

