# TCL File Generated by Component Editor 18.1
# Sun Mar 22 23:54:07 GMT 2020
# DO NOT MODIFY


# 
# ci_expr "ci_expr" v1.0
#  2020.03.22.23:54:07
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module ci_expr
# 
set_module_property DESCRIPTION ""
set_module_property NAME ci_expr
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME ci_expr
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL expr
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file expr.v VERILOG PATH ip/expr/expr.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point ci_expr_slave
# 
add_interface ci_expr_slave nios_custom_instruction end
set_interface_property ci_expr_slave clockCycle 39
set_interface_property ci_expr_slave operands 1
set_interface_property ci_expr_slave ENABLED true
set_interface_property ci_expr_slave EXPORT_OF ""
set_interface_property ci_expr_slave PORT_NAME_MAP ""
set_interface_property ci_expr_slave CMSIS_SVD_VARIABLES ""
set_interface_property ci_expr_slave SVD_ADDRESS_GROUP ""

add_interface_port ci_expr_slave x dataa Input 32
add_interface_port ci_expr_slave result result Output 32
add_interface_port ci_expr_slave clk clk Input 1
add_interface_port ci_expr_slave reset reset Input 1

